### ISSUE TITLE
WhereOpCall parse error

### ISSUE THREAD

**Issue by domluna** [ZacLN/CSTParser.jl#93]
```julia
julia> str
"f(a, b, c)::Rtype where {A,B,C}"

julia> CSTParser.parse(str)
BinarySyntaxOpCall  31 (31)
 Call  10 (10)
  ID: f  1 (1)
  (
  ID: a  1 (1)
  ,
  ID: b  1 (1)
  ,
  ID: c  1 (1)
  )
 OP: DECLARATION  2 (2)
 WhereOpCall  19 (19)
  ID: Rtype  6 (5)
  OP: WHERE  6 (5)
  PUNC: LBRACE  1 (1)
  ID: A  1 (1)
  ,
  ID: B  1 (1)
  ,
  ID: C  1 (1)
  PUNC: RBRACE  1 (1)
```

I think this should be a WhereOpCall at the top-level and arg1 would be the BinarySyntaxOpCall.

**Comment by ZacLN** [comment]
Hiya,
```julia
versioninfo() # Julia Version 1.2.0-DEV.291
str = "f(a, b, c)::Rtype where {A,B,C}"
Expr(CSTParser.parse(str)) == Meta.parse(str) #true
```
I don't think this has changed recently

**Comment by domluna** [comment]
So would this be an upstream issue with julia then? It seems weird that it would be parsed this way.

**Comment by ZacLN** [comment]
This is just a result of the levels of precedence for `::` and `where`. In this case it is slightly 
odd because while the the `where` expression is separate from the `call` expression the scope of the `where` block would actually include the call (I assume this expression is from a function assignment). I doubt there's a clean solution to this, and certainly not by making `::` lower precedence than `where`.

**Comment by domluna** [comment]
Hmm in that case it's probably not worth doing anything. Originally I thought this caused a very minor bug in JLFmt where it doesn't nest as soon as it could but looking it this more it has nothing to do with the way this is parsed.
